GET http://localhost:3000 HTTP/1.1

###

GET http://localhost:3000/task HTTP/1.1

###


GET http://localhost:3000/task/ae2d5b14-6584-4b7c-8944-fdbee3be85cb HTTP/1.1

###

POST http://localhost:3000/task HTTP/1.1
Content-Type: application/x-www-form-urlencoded

title=foo
&description=bar

###
DELETE http://localhost:3000/task/2d691bf5-67ba-4e82-b0bd-4671bdde1f50 HTTP/1.1

###

PATCH  http://localhost:3000/task/4f451472-076d-4748-8fae-223da1d478de/status HTTP/1.1
Content-Type: application/x-www-form-urlencoded

status=DONE

###

POST http://localhost:3000/signup HTTP/1.1
Content-Type: application/x-www-form-urlencoded

title=foo
&description=bar


